# Generated by Django 5.2.5 on 2025-08-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('github_link', models.URLField()),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('is_mobile_app', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('outcome', models.TextField()),
            ],
        ),
    ]
