# Generated by Django 5.2.5 on 2025-09-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscreenshot',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
    ]
